# Generated by Django 4.2.7 on 2025-10-01 19:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('earth_health', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('power_grid', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('satellites', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('communications', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rank', models.CharField(blank=True, choices=[('BEGINNER', 'Space Beginner'), ('CADET', 'Space Cadet'), ('COMMANDER', 'Space Commander'), ('MASTER', 'Solar Defender Master')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolarFlare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flare_id', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=10)),
                ('flare_class', models.CharField(choices=[('A', 'A-Class'), ('B', 'B-Class'), ('C', 'C-Class'), ('M', 'M-Class'), ('X', 'X-Class')], max_length=1)),
                ('intensity', models.FloatField()),
                ('begin_time', models.DateTimeField()),
                ('is_simulation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-begin_time'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_choice', models.IntegerField(choices=[(1, 'Satellite Shields'), (2, 'Grid Protection'), (3, 'Communications Boost'), (4, 'Integrated Defense')])),
                ('success', models.BooleanField(default=True)),
                ('phase_number', models.IntegerField()),
                ('power_grid_after', models.IntegerField()),
                ('satellites_after', models.IntegerField()),
                ('communications_after', models.IntegerField()),
                ('earth_health_after', models.IntegerField()),
                ('points_earned', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_defender.solarflare')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='solar_defender.gamesession')),
            ],
            options={
                'ordering': ['phase_number'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='solar_defender.player'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_position', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_defender.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_defender.gamesession')),
            ],
            options={
                'ordering': ['rank_position'],
                'unique_together': {('player', 'session')},
            },
        ),
    ]
