# Generated by Django 5.2.4 on 2025-09-30 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarFlare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flare_id', models.CharField(max_length=100, unique=True)),
                ('class_type', models.CharField(max_length=10)),
                ('flare_class', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('M', 'Class M'), ('X', 'Class X')], max_length=1)),
                ('intensity', models.FloatField()),
                ('begin_time', models.DateTimeField()),
                ('peak_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('risk_level', models.CharField(max_length=20)),
                ('risk_color', models.CharField(max_length=7)),
                ('impact_effects', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solar Flare',
                'verbose_name_plural': 'Solar Flares',
                'ordering': ['-begin_time'],
            },
        ),
        migrations.CreateModel(
            name='SpaceWeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_flares', models.IntegerField(default=0)),
                ('risk_percentage', models.FloatField(default=0.0)),
                ('prediction_confidence', models.FloatField(default=92.7)),
                ('strongest_flare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strongest_reports', to='weather_api.solarflare')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
